///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package SAResultMiner;
//
//import org.junit.Test;
//
//import edu.handong.csee.isel.saresultminer.Main;
//
//import static org.junit.Assert.*;
//
//public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Main classUnderTest = new Main();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//}
